options:
  install_sources:
    default: |
      - deb http://nightly.odoo.com/10.0/nightly/deb/ ./
  install_keys:
    default: |
      - DEF2A2198183CBB5
  dbname:
    default: odoo
  port:
    default: 80
